# Generated by Django 3.2 on 2021-05-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0012_classroom_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=2048)),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
