# Generated by Django 3.2 on 2021-05-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportclassroom',
            old_name='Day',
            new_name='day',
        ),
    ]
