# Generated by Django 3.2 on 2021-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_day_reportclassroom_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportclassroom',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
