# Generated by Django 3.2 on 2021-05-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.CharField(max_length=12),
        ),
    ]
