# Generated by Django 3.2 on 2021-05-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_auto_20210517_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
