# Generated by Django 3.2 on 2021-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_auto_20210519_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
