# Generated by Django 3.2 on 2021-06-01 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_classroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='publishing_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
