# Generated by Django 3.2 on 2021-06-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0014_questionsqanda_replyqanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyqanda',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom'),
        ),
    ]
