# Generated by Django 3.2 on 2021-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_remove_messageadmin_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageadmin',
            name='content',
            field=models.CharField(max_length=2048),
        ),
    ]
